version: "3.3"

services:

  skill:
    container_name: mul_table_skill
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main_mul_table.py
    restart: "on-failure"
    ports:
      - 5000:5000
